### ISSUE TITLE
Different credentials

### ISSUE THREAD

**Issue by ozstriker** [GrahamCampbell/Laravel-Bitbucket#10]
Hi! 
Can I use the package somehow with different credentials for every website user?

Thanks

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by ozstriker** [comment]
Can you, please, give a quick hint how can I do that? Tnx

**Comment by GrahamCampbell** [comment]
Resolve this class out of the container, and call make on it: https://github.com/GrahamCampbell/Laravel-Bitbucket/blob/master/src/BitbucketFactory.php. You can also access that class like this:

```php
Bitbucket::getFactory()->make([['method'  => 'token', 'token' => 'your-token']]);
```
