### ISSUE TITLE
received data format issue

### ISSUE THREAD

**Issue by nitish1986** [GrahamCampbell/Laravel-Bitbucket#11]
Hello,

I'm using your codes in my application built on `laravel 5.5`, where I'm facing some problem, I'm trying to retrieve list of commit details for my repository and I'm unable to use the response format. I'm trying to do something like this:

    $data = Bitbucket::api('Repositories\Commits')->all('***repo***user***', '***repo***name***', array(
                'branch' => 'master'
    ));
    return $data

I'm getting a response which is not in JSON format:

	HTTP/1.1 200 OK
	Server: nginx
	Vary: Authorization
	Vary: Accept-Encoding
	Content-Type: application/json; charset=utf-8
	Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
	Date: Tue, 13 Feb 2018 09:21:41 GMT
	X-Served-By: app-139
	ETag: "7b8332218b7bc6b7c4a2f50e3ab9c45c"
	X-Static-Version: 476dd7889f1a
	X-Content-Type-Options: nosniff
	X-Accepted-OAuth-Scopes: repository
	X-Credential-Type: password
	X-Render-Time: 1.31000494957
	Connection: keep-alive
	X-Request-Count: 141
	X-Frame-Options: SAMEORIGIN
	Last-Modified: Mon, 12 Feb 2018 20:17:03 GMT
	X-Version: 476dd7889f1a
	Content-Length: 71360

	{"pagelen": 30, "values": [{"hash": "********9b580ff91967547d61*****", "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/********/*****"}, "html": {"href......

I've already tried return `response()->json(['data' => $data], 200)` which was giving me no data. I can see headers data is also coming, if I use `json_decode($data)` it is gives me error which clearly shows is not a JSON. How can I format this to a proper JSON response?

**Comment by GrahamCampbell** [comment]
Sorry, this doesn't really relate to this package.

**Comment by nitish1986** [comment]
I guess I'll have to explain in better way. Following is my code in controller:

	<?php

	namespace App\Http\Controllers;

	use GrahamCampbell\Bitbucket\Facades\Bitbucket;
	use Illuminate\Http\Request;

	class TestController extends Controller
	{
		public function commentTest()
		{
			$data = Bitbucket::api('Repositories\Repository')->get('noeticitservices', 'nitseditor');
			return response()->json(['data' => $data], 200);
		}
	}

I'm unable to get any response in this, now if I do `return $data` I get following data:

	HTTP/1.1 200 OK
	Server: nginx
	Vary: Authorization
	Vary: Accept-Encoding
	Content-Type: application/json; charset=utf-8
	Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
	Date: Tue, 13 Feb 2018 09:21:41 GMT
	X-Served-By: app-139
	ETag: "7b8332218b7bc6b7c4a2f50e3ab9c45c"
	X-Static-Version: 476dd7889f1a
	X-Content-Type-Options: nosniff
	X-Accepted-OAuth-Scopes: repository
	X-Credential-Type: password
	X-Render-Time: 1.31000494957
	Connection: keep-alive
	X-Request-Count: 141
	X-Frame-Options: SAMEORIGIN
	Last-Modified: Mon, 12 Feb 2018 20:17:03 GMT
	X-Version: 476dd7889f1a
	Content-Length: 71360


	{"pagelen": 30, "values": [{"hash": "********9b580ff91967547d61*****", "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/********/*****"}, "html": {"href......

Which should be actually:

	{"pagelen": 30, "values": [{"hash": "********9b580ff91967547d61*****", "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/********/*****"}, "html": {"href......

But somehow I'm also getting this:

    HTTP/1.1 200 OK
    Server: nginx
    Vary: Authorization
    Vary: Accept-Encoding
    Content-Type: application/json; charset=utf-8
    .
    .
    .

For more relevance let me show you the screenshot:

![image](https://user-images.githubusercontent.com/17726431/36168617-b10fb9ca-111f-11e8-899f-1c4a4b195d19.png)

Moreover in browser dom when called:

![image](https://user-images.githubusercontent.com/17726431/36168851-74fa0e08-1120-11e8-910f-0a4b01b73f64.png)

I've not used any of the feature except your facade, hope you get what is the issue. Thank you for your time.
