### ISSUE TITLE
Oauth 2 Consumer

### ISSUE THREAD

**Issue by lukesnowden** [GrahamCampbell/Laravel-Bitbucket#14]
Is there any way to use the Bitbucket Oauth 2 consume key and secret credentials with this package?

**Comment by GrahamCampbell** [comment]
Yeh, see the example config file. :) This package does not do the actual flow part for you, however. There are lots of other packages that do oauth flow. You just need to give this package the resulting token.

**Comment by vesper8** [comment]
soo.. if I understand correctly the answer is that no this package doesn't work if all you've done is created an oauth consumer and gotten the key and secret. Because the config file does not accept that key and secret, instead you have to use the key and secret with an oauth flow and once you've gotten the token from that, then you can pass that to the config file

**Comment by lukesnowden** [comment]
> soo.. if I understand correctly the answer is that no this package doesn't work if all you've done is created an oauth consumer and gotten the key and secret. Because the config file does not accept that key and secret, instead you have to use the key and secret with an oauth flow and once you've gotten the token from that, then you can pass that to the config file

Yeah thats what I thought, ended up just using my bitbucket username and password for testing and ended leaving it. This package seems to do what you are after; https://github.com/stevenmaguire/oauth2-bitbucket

**Comment by vesper8** [comment]
@lukesnowden I wouldn't do that if I were you.. instead what you can do is create an "App Password" which you will also use with your username. It will grant you as much access as you associate to it but without exposing your full access admin web username/password. That's what I'm doing now and it's working very well

**Comment by lukesnowden** [comment]
@vesper8 Did not know bitbucket had App Passwords, cheers! FYI https://confluence.atlassian.com/bitbucket/app-passwords-828781300.html
