### ISSUE TITLE
Download a repository

### ISSUE THREAD

**Issue by ilongley** [GrahamCampbell/Laravel-Bitbucket#20]
Is there anyway to download a repository using this package? It's the last part of the puzzle I have yet to solve!

**Comment by GrahamCampbell** [comment]
I don't think Bitbucket support doing this? You should checkout out the code using git if you want the actual but repository download.

**Comment by ilongley** [comment]
I came across this - https://community.atlassian.com/t5/Bitbucket-questions/How-to-download-repository-as-zip-file-using-the-API/qaq-p/862113

It appears that it's supported by the api, so I should be able to figure something out as I can get the repo branch metadata from your package and build the call myself.

Thanks for the quick response!

**Comment by GrahamCampbell** [comment]
If it's supported by the API, then I will have implemented it already.

**Comment by GrahamCampbell** [comment]
That link you posted there says that it's not supported by the API. It instructs you to directly visit https://bitbucket.org/<username>/<repo-name>/get/master.zip. Note that this does not download the repository. It will only download the current state of the master branch.

**Comment by GrahamCampbell** [comment]
> Edit: I should add that the need to download the repo is to move a copy to cloud storage as part of a archiving backup process.

Note that this does not download the repository. It will only download the current state of the master branch.

**Comment by ilongley** [comment]
Ah you are correct, I misread.

Back to the drawing board by the looks of it then...

**Comment by ilongley** [comment]
Is there any way to perform a get request using your package, as we authenticate when initialising the connection?

**Comment by GrahamCampbell** [comment]
I'd encourage you to read the source code to see how things are working behind the scenes. Ultimately, when you call the Bitbucket facade, you calls are forwarded to https://github.com/BitbucketAPI/Client/blob/v2.0.2/src/Client.php. You can get the authenticated HTTP client by calling `getHttpClient();` (an instance of https://github.com/php-http/client-common/blob/v1.6.0/src/HttpMethodsClient.php).

**Comment by GrahamCampbell** [comment]
For repos that are not public, I doubt bitbucket accepts the same authentication as the api itself accepts, but you can probably try and see what happens.

**Comment by ilongley** [comment]
Thanks for the pointers Graham, much appreciated. I'll take a look and give it a go.

Thanks again.

**Comment by ilongley** [comment]
$http = Bitbucket::connection('alternative')->getHttpClient();
return $http->get('https://bitbucket.org/ilongley/project/get/develop.zip', []);

Works like a charm, and the repo is private!

Thanks for all your help.

**Comment by GrahamCampbell** [comment]
Great.
