### ISSUE TITLE
setPerPage() doesn't seem to work for repositories

### ISSUE THREAD

**Issue by LesleyKras** [GrahamCampbell/Laravel-Bitbucket#23]
Hi there!
I've been trying to get a certain amount of repositories from BitBucket by making use of the Laravel-Bitbucket package. According to the docs, it should be possible to define the amount of results you'd like to receive on different API endpoints by calling the setPerPage() function.

When doing so with the members endpoint like in the example below, I get the specified amount of results back, as expected:
```
$team = Bitbucket::teams('teamname');

$members = $team->members();
$members->setPerPage(20);
$members->list();
```

However, when doing the exact same thing for the repositories endpoint. I keep ending up with the default amount of 10 repositories per page instead of the specified amount (20 in the example below).

```
$team = Bitbucket::teams('teamname');

$repositories = $team->repositories();
$repositories->setPerPage(20);
$repositories->list();
```
Am I doing something wrong here or is this a bug?
Could you please look into this?

Thank you in advance!

**Comment by GrahamCampbell** [comment]
I'm not sure. What happens when you construct the request yourself in the cli, say, with curl. Does Bitbucket's API respect the number per page you ask for?
