### ISSUE TITLE
Getting all branches from a repository?

### ISSUE THREAD

**Issue by alexeightsix** [GrahamCampbell/Laravel-Bitbucket#25]
How can I get all the branches from a repo?

**Comment by GrahamCampbell** [comment]
There are some examples at https://github.com/GrahamCampbell/Laravel-Bitbucket#real-examples. For getting branches, just look at the [source code](https://github.com/BitbucketAPI/Client/tree/master/src) or [generated docs](https://bitbucketapi.github.io/Client/), and follow the methods. They match up with the [Bitbucket API docs](https://developer.atlassian.com/bitbucket/api/2/reference/).

**Comment by GrahamCampbell** [comment]
Here's an example that will paginate all the branches:

```
$client = Bitbucket::connection('main'); // for example (replace me with whatever)

$branches = (new Bitbucket\ResultPager($client))->fetchAll(
    $client->repositories()->users('TEAMNAME')->refs('REPONAME')->branches(),
    'list'
);
```
