### ISSUE TITLE
The purpose of the package is not very clear

### ISSUE THREAD

**Issue by vernard** [GrahamCampbell/Laravel-Bitbucket#3]
Hi.

I'm trying to understand what this package can do but it seems I have to read the whole docs and the codes first.

I think it would be helpful to document that. Actually, please do it.

**Comment by vernard** [comment]
Actually. I think I'm just too lazy. Sorry. I'll google what the bitbucket API docs.

**Comment by ryancwalsh** [comment]
I agree. I couldn't figure out how to use this at all. Here is what I did instead: https://github.com/BitbucketAPI/Client/issues/14
